[package]
name = "simple-psf"
version = "0.1.2"
edition = "2021"
license = "MIT"
authors = ["Jayshua Nelson <me@jayshuanelson.com>"]
repository = "https://github.com/Jayshua/simple-psf"
description = "A simple library for parsing PSF bitmap font files."

[dependencies]
